# This is a basic workflow to help you get started with Actions

name: js-lint

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main
      - joelmut/test/checks
    paths:
      - samples/javascript_es6/*
      - samples/javascript_nodejs/*
      - samples/typescript_nodejs/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ci:
    # The type of runner that the job will run on
    name: lint
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: use node 16.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: 16.x

      - name: yarn lint
        run: yarn lint
